export const ADD_NEW_FILM_REQUEST = 'ADD_NEW_FILM_REQUEST';
export const ADD_NEW_FILM_SUCCESS = 'ADD_NEW_FILM_SUCCESS';
export const ADD_NEW_FILM_FAIL = 'ADD_NEW_FILM_FAIL';
export const CLEAR_NEW_FILM = 'CLEAR_NEW_FILM';