export const MANAGE_CINEMA_REQUEST = 'MANAGE_CINEMA_REQUEST';
export const MANAGE_CINEMA_SUCCESS = 'MANAGE_CINEMA_SUCCESS';
export const MANAGE_CINEMA_FAIL = 'MANAGE_CINEMA_FAIL';
export const DETAIL_CINEMA_REQUEST = 'MANAGE_CINEMA_REQUEST';
export const DETAIL_CINEMA_SUCCESS = 'MANAGE_CINEMA_SUCCESS';
export const DETAIL_CINEMA_FAIL = 'MANAGE_CINEMA_FAIL';
